from django.conf.urls import url
from . import views

urlpatterns=[


url(r'^known/$',views.KnownFaces,name="KnownFaces"),
url(r'^unknown/$',views.UknownFaces,name="UknownFaces"),
url(r'^login$',views.login,name="login"),
url(r'^login$',views.login,name="login"),
url(r'^$',views.indexpage,name="indexpage"),
url(r'^signup$',views.signup,name="signup"),
url(r'^logout$',views.logoutuser,name="logoutuser"),
url(r'^training$',views.TrainingFaces,name="TrainingFaces"),
url(r'^usertagging/(?P<userid>[A-Za-z0-9\w @%&._ -]+)/$', views.UserTagging,name="UserTagging"),
url(r'^test/$',views.test,name="test"),
url(r'^lprdetect/$',views.Numberplate,name="Numberplate"),
url(r'^clear/$',views.ClearAll,name="ClearAll"),
url(r'^ledger/$',views.Ledger,name="Ledger"),
url(r'^editinfo/$',views.EditInfo,name="EditInfo"),
url(r'^timelinepopup/$',views.TimelinePopup,name="TimelinePopup"),
url(r'^popuptagging/$',views.PopUpUserTagging,name="PopUpUserTagging"),
url(r'^delete/(?P<userid>[A-Za-z0-9\w @%&._ -]+)/$',views.DeleteRecord,name="DeleteRecord"),
url(r'^multitraining/$',views.MultiTraining,name="MultiTraining"),
url(r'^LedgerPopup/$',views.LedgerPopup,name="LedgerPopup"),
url(r'^timeline-addname/$',views.timelineaddname,name="timelineaddname"),
url(r'^timeline-editname/$',views.timelineeditname,name="timelineeditname"),
url(r'^timeline-delete/$',views.timelinedeletename,name="timelinedeletename"),
url(r'^timelin-einfo/$',views.timelineinfo,name="timelineinfo"),
url(r'^multiedit/$',views.MultiEdit,name="MultiEdit"),
url(r'^multidelete/$',views.DeleteMultiple,name="DeleteMultiple"),
url(r'^infotimeline/$',views.infotimeline,name="infotimeline"),
url(r'^multiinfo/$',views.multiinfo,name="multiinfo"),
url(r'^events/$',views.eventresults,name="eventresults"),
url(r'^complete-timeline/$',views.Completetimeline,name="Completetimeline"),
url(r'^getinfo/$',views.GetInfo,name="GetInfo"),
url(r'^trainedpeoplegroup/$',views.TrainedPeopleGroup,name="TrainedPeopleGroup"),
url(r'^reports/$',views.VisitingReports,name="VisitingReports"),
url(r'^videos/$',views.Videos,name="Videos"),
url(r'^addcamera/$',views.addcamera,name="addcamera"),
url(r'^eventresults/$',views.eventresults,name="eventresults"),
url(r'^download/(?P<eid>[0-9]+)/$',views.download,name="download"),
url(r'^deletevideo/(?P<eid>[0-9]+)/$',views.deletevideo,name="deletevideo"),
url(r'^trainsvm/$',views.trainsvm,name="trainsvm"),
url(r'^lock/$',views.Lockscreen,name="Lockscreen"),
]